spring.application.name=springsecurity

#spring.security.user.name=urvish
#spring.security.user.password=urvish2004


spring.datasource.url=jdbc:mysql://localhost:3306/security1?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=Urvish@2004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

